var n = 10;
console.log("number : ", n);
var s = "Pratik";
console.log("String: ", s);
var nu = null;
console.log("null", nu);
var isDone = true;
console.log("boolean", isDone);
var und = undefined;
console.log("undefined", und);
var arr = [1, 2, 3, 4, 5];
console.log("array", arr);
var tup = ["Pratik", 10];
tup = ["p", 3];
console.log("Tuple: ", tup);
